import assert from 'node:assert/strict';
import test from 'node:test';
import { numberOrNull, preflightDelta, noOrderReasons, reconciliationEvidence, feeEvidence, capitalAllowance, deploymentChanges, orderInvestigation, stopEffects } from '../src/operatorInsights.js';
const context = {id:'view',strategyId:'s1',brokerId:'kis',symbol:'005930'};
const base = {api_connected:true, accounts:[{broker_id:'kis',currency:'KRW'}],positions:[{broker_id:'kis',symbol:'005930',currency:'KRW',broker_qty_value:2,current_price:100,program_qty_value:1}],orders:[]};
test('missing/false/empty values never become zero',()=>{for(const value of [null,undefined,false,true,'',NaN,'wat'])assert.equal(numberOrNull(value),null);assert.equal(numberOrNull(0),0);});
test('preflight new/resolved/escalated/removed are distinct',()=>{const view=preflightDelta([{checks:[{label:'new',status:'fail'},{label:'resolved',status:'pass'},{label:'worse',status:'fail'},{label:'same',status:'warn'}]},{checks:[{label:'resolved',status:'fail'},{label:'gone',status:'fail'},{label:'worse',status:'warn'},{label:'same',status:'warn'}]}]);assert.deepEqual(view.newIssues.map(x=>x.label),['new','worse']);assert.equal(view.resolved.length,1);assert.equal(view.removed.length,1);assert.equal(view.unchanged.length,1);});
test('first check makes no invented resolved result',()=>{assert.equal(preflightDelta([{checks:[{label:'a',status:'fail'}]}]).first,true);assert.equal(preflightDelta([]).known,false);});
test('stopped and disconnected are not normal no-signal claims',()=>{assert.equal(noOrderReasons({...base,continuous_runtime:{running:false}},context)[0].category,'조건 대기');assert.equal(noOrderReasons({},context)[0].category,'상태 미확인');});
test('only verified evaluation from this running deployment can say no signal',()=>{const data={...base,continuous_runtime:{profiles:{stock:{running:true,profileId:'stock',deploymentId:'view',mode:'FULL_LIVE'}}},strategy_runner:{last_profile:'stock',last_strategy:'s1',last_run:'2026-09-10T00:00:00Z',last_market_verified:true,last_signal:'HOLD'}};assert.ok(noOrderReasons(data,context).some(x=>x.category==='신호 없음'));data.strategy_runner.last_strategy='other';assert.ok(!noOrderReasons(data,context).some(x=>x.category==='신호 없음'));});
test('kill and authority restrictions remain separate',()=>{const result=noOrderReasons({...base,kill_switch:true,dry_run:true},context);assert.ok(result.some(x=>x.category==='위험 제한'));assert.ok(result.some(x=>x.category==='권한 없음'));});
test('reconciliation zero and missing qty and hedged paths survive',()=>{const result=reconciliationEvidence({positions:[{symbol:'BTC',position_side:'LONG',program_qty_value:0,broker_qty_value:2},{symbol:'BTC',position_side:'SHORT',program_qty_value:1,broker_qty_value:null}]});assert.equal(result.positions[0].difference,2);assert.equal(result.positions[1].difference,null);assert.equal(result.positions.length,2);});
test('unlabelled fees cannot become confirmed KRW costs',()=>{assert.equal(feeEvidence({raw:{fee:0}}).verified,false);assert.deepEqual(feeEvidence({raw:{fee:2,fee_currency:'USDT',fee_mode:'cumulative'}}),{fee:2,currency:'USDT',mode:'누계',verified:true});});
test('capital shows current usage remaining overage and pending separately',()=>{const view=capitalAllowance({...base,orders:[{broker_id:'kis',symbol:'005930',state:'UNKNOWN'}]},context,300);assert.equal(view.used,200);assert.equal(view.remaining,100);assert.equal(view.pending,1);assert.equal(capitalAllowance(base,context,100).over,100);});
test('foreign/futures or unknown prices cannot be treated as KRW zero',()=>{for(const positions of [[],[{...base.positions[0],currency:'USD'}],[{...base.positions[0],current_price:null}],[{...base.positions[0],broker_qty_value:null}]])assert.equal(capitalAllowance({...base,positions},context,300).remaining,null);assert.equal(capitalAllowance(base,{...context,brokerId:'binance-futures'},300).remaining,null);assert.equal(capitalAllowance({...base,positions:[{...base.positions[0],broker_qty_value:0,current_price:null}]},context,300).remaining,300);});
test('deployment compares real zero and removes only confirmed members',()=>{const before={metadata:{allowedSymbols:['A']},reviewWeights:{'a:A':.5,'b:B':0},reviewRisk:{max:0}};const after={metadata:{allowedSymbols:['B','A']},reviewWeights:{'a:A':0,'c:C':null},reviewRisk:{max:1}};const view=deploymentChanges({before,after});assert.ok(view.changes.find(row=>row.label==='목표 비중 a:A'&&row.after==='0%'));assert.ok(view.changes.find(row=>row.label==='목표 비중 b:B'&&row.after==='구성에서 제외'));assert.ok(view.changes.find(row=>row.label==='위험 설정 max'));assert.equal(deploymentChanges({}).known,false);});
test('unconfirmed order includes only exact owned order evidence, account success not order resolution',()=>{const result=orderInvestigation({durable_audit:[{order_id:'one',broker_id:'kis'},{order_id:'one',broker_id:'upbit'},{order_id:'two',broker_id:'kis'}],execution_events:{recent:[{order_id:'one',broker_id:'kis',occurred_at:'2026-09-10T00:00:00Z'}]},reconciliation:{summary:{last_run:'2026-09-10T01:00:00Z',status:'pass'}}},{order_id:'one',broker_id:'kis',state:'UNKNOWN',reconciliation_warning:'접수 미확정'});assert.equal(result.audit.length,1);assert.equal(result.reason,'접수 미확정');assert.equal(result.lastAccountReconciliation,'2026-09-10T01:00:00Z');assert.notEqual(result.lastExecution,result.lastAccountReconciliation);});
test('stop comparison never promises liquidation or guaranteed cancellation',()=>{assert.equal(stopEffects.length,3);assert.ok(stopEffects[1][2].includes('자동 취소하지'));assert.ok(stopEffects[2][2].includes('실패/미확정'));assert.ok(stopEffects.every(row=>row[3].includes('유지')));});

test('missing symbol metadata remains unknown while explicit empty arrays are comparable',()=>{assert.ok(deploymentChanges({before:{metadata:{}},after:{metadata:{}}}).unknown.some(value=>value.startsWith('대상 종목')));assert.ok(!deploymentChanges({before:{metadata:{allowedSymbols:[]}},after:{metadata:{allowedSymbols:[]}}}).unknown.some(value=>value.startsWith('대상 종목')));});

test('current exact-scope risk rejection is classified separately, old or other orders are not',()=>{const data={...base,continuous_runtime:{profiles:{stock:{running:true,profileId:'stock',deploymentId:'view'}}},strategy_runner:{last_profile:'stock',last_strategy:'s1',last_run:'2026-09-10T00:00:00Z'},orders:[{deployment_id:'view',time:'2026-09-10T00:00:00Z',risk_report:{can_submit:false},reason:'한도 초과'}]};assert.ok(noOrderReasons(data,context).some(x=>x.category==='위험 제한'));data.orders[0].deployment_id='other';assert.ok(!noOrderReasons(data,context).some(x=>x.category==='위험 제한'));});
